name: auto commit
on: push

jobs:
  post-auto-commit:
    name: "금일 알고리즘 문제 풀이"
    runs-on: ubuntu-latest
    steps:
      - name: Date setting
        run: echo DATE=$(date +'%Y년-%m월-%d일') >> $GITHUB_ENV
      
      # repository 정보를 읽어온다.
      - name: repo checkout
        uses: actions/checkout@v2
          
      # 커밋을 수정한다.
      - name: post auto commit
        run:  |
          git config --global user.name 'Jooney-95'
          git config --global user.email 'xmun777@naver.com'
          git add -A
          git commit -am "${{ env.DATE }} 알고리즘 문제풀이"
          git push
