name: auto commit
on: push

jobs:
  Post-Auto-Commit:
    name: "금일 알고리즘 문제 풀이"
    runs-on: ubuntu-latest
    steps:
      - name: Date setting
        run: echo DATE=$(date +'%Y년-%m월-%d일') >> $GITHUB_ENV

      - name: repo checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.md'
          disable_globbing: true   
        
        
        
#       - name: overlap commit
#         uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           commit_message: ${{ env.DATE }} 문제 풀이 기록
#           commit_user_name: langoustine
#           commit_author: "xmun777@naver.com"
