name: auto commit
on: push

jobs:
  Post-Auto-Commit:
    name: "금일 알고리즘 문제 풀이"
    runs-on: ubuntu-latest
    steps:
      - name: Date setting
        run: echo DATE=$(date +'%Y년-%m월-%d일') >> $GITHUB_ENV

      - name: repo checkout
        uses: actions/checkout@v2
        
      - name: print git log
        run: echo $(git log -5 --oneline)
