# This is a basic workflow to help you get started with Actions

name: daily-cron


on:
  schedule:
    - cron: '0 0/5 * * * ?'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
