name: github-actions-demo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run cd _posts/algorithm
        run: cd _posts/algorithm
        
      - name: Run ls -al
        run: ls -al
        
      - name: search baekjoon dir post
        run: find _posts/algorithm/baekjoon/ -type f -ctime -1;

      - name: search programmers dir post
        run: find _posts/algorithm/programmers/ -type f -ctime -1;
        
        
